channel_sources:
  - cryoem, conda-forge            # [unix]
  - cryoem, conda-forge, defaults  # [win]
channel_targets:
- cryoem main
c_compiler:    # [win]
  - vs2017       # [win]
cxx_compiler:  # [win]
  - vs2017       # [win]

pyqt:
  - 5
pyopengl:
  - 3.1.5
nodejs:
  - '*'
pydusa:
  - 3.1

pin_run_as_build:
  pyqt:
    max_pin: x.x
  pyopengl:
    max_pin: x.x
  pydusa:
    max_pin: x.x.x

ignore_version:
  - nodejs
