channel_sources:
  - cryoem, conda-forge            # [unix]
  - cryoem, conda-forge, defaults  # [win]
channel_targets:
- cryoem main
cos:                               # [linux]
  - cos6                           # [linux]
  - cos7                           # [linux]
