pipeline {
  agent {
    node { label "linux" }
  }

  stages {
    stage('bump version') {
      steps {
        sh 'env | sort'
        sh 'python ./recipe/update-eman-feedstock.py'
      }
    }
  }
}
