{% set repo   = "eman2" %}
{% set branch = "master" %}

package:
  name: eman-dev
  version: 2.99

source:
  - git_url: https://github.com/cryoem/eman2.git
    git_rev: master
    git_depth: 1
  - url: https://www.khronos.org/registry/OpenGL/api/GL/glext.h             # [win]
    folder: GL                                                              # [win]
  - url: https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h         # [win]
    folder: KHR                                                             # [win]

build:
  number: 25

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17              # [linux64]
    - make                               # [unix]

  host:
    - eman-deps         31.1
    - libglu                             # [linux]

  run:
    - eman-deps         31.1

test:
  requires:
    - eman-deps         31.1
    - openssh                            #[not win]

  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]

about:
  summary: Eman development package
