{% set version = "2.99.63" %}
{% set tag = "v" + version %}
{% set build = 0 %}

# prioritize gui variant via build number
{% if ui == 'gui' %}
{% set build = build  + 100 %}
{% endif %}

package:
  name: eman-dev
  version: {{ version }}

source:
  - url: https://github.com/cryoem/eman2/archive/{{ tag }}.tar.gz
    fn: eman2-{{ tag }}.tar.gz
  - url: https://www.khronos.org/registry/OpenGL/api/GL/glext.h             # [win]
    folder: GL                                                              # [win]
  - url: https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h         # [win]
    folder: KHR                                                             # [win]

build:
  number: {{ build }}
  # add build string so packages can depend on
  # gui or nogui variants explicitly:
  # `pkg * gui_*` for any gui
  # `pkg * nogui_*` for no gui
  string: "{{ ui }}_h{{ PKG_HASH }}_{{ build }}"
  skip: True  # [py != 312 and linux]
  skip: True  # [py != 312 and osx]
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17              # [linux64]
    - make                               # [unix]
    - python                             # [build_platform != target_platform]
    - cmake                              # [build_platform != target_platform]
    - numpy                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }} # [build_platform != target_platform]

  host:
    - python
    - pip
    - pyqt                               # [ui == 'gui']
    - pyopengl                           # [ui == 'gui']
    - cmake        >=3.14

    - ipywidgets
    - matplotlib
    - scipy
    - ipython
    - scikit-learn
    - pandas
    - tensorflow
    - tf-keras
    - pydusa                             # [not win]
    - future
    - configparser
    - tqdm
    - jupyterlab
    - nodejs
    - biopython
    - umap-learn

    - boost
    - fftw
    - numpy
    - ftgl
    - freetype
    - gsl
    - hdf5         >=1.12                # [not win]
    - hdf5         <1.14                 # [win]
    - libtiff
    - libpng
    - zlib

  run:
    - python
    - pyqt                               # [ui == 'gui']
    - pyopengl                           # [ui == 'gui']
    - cmake        >=3.14

    - ipywidgets
    - matplotlib
    - scipy
    - ipython
    - scikit-learn
    - pandas
    - tensorflow
    - tf-keras
    - pydusa                             # [not win]
    - future
    - configparser
    - tqdm
    - jupyterlab
    - nodejs
    - biopython
    - umap-learn

    - boost
    - fftw
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - ftgl
    - freetype
    - gsl
    - hdf5         >=1.12                # [not win]
    - hdf5         <1.14                 # [win]
    - libtiff
    - libpng
    - zlib

about:
  summary: Eman development package
