{% set repo   = "eman2" %}
{% set branch = "develop" %}

package:
    name: eman-dev
    version: 2.39

source:
    url: https://github.com/cryoem/{{ repo }}/archive/{{ branch }}.tar.gz
    fn: {{ repo }}-{{ branch }}.tar.gz

build:
  number: 0
  skip: True  # [win32]

requirements:
  build:
    - cmake     3.14.*
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}   # [linux]

  host:
    - python    3.6.*
    - boost     1.66.*
    - fftw-mpi
    - numpy     1.13.*
    - ftgl
    - freetype
    - gsl
    - hdf5      1.8.18
    - jpeg
    - libtiff   4.0.9
    - libpng    1.6.36
    - zlib
    - libglu                          # [linux]

  run:
    - eman-deps

test:
  source_files:
    - examples/mpi_test.py
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]

about:
  summary: Eman development package
