{% set version = "2.99.34" %}
{% set tag = "v" + version %}
{% set emandeps = "33.1" %}

package:
  name: eman-dev
  version: {{ version }}

source:
  - url: https://github.com/cryoem/eman2/archive/{{ tag }}.tar.gz
    fn: eman2-{{ tag }}.tar.gz
  - url: https://www.khronos.org/registry/OpenGL/api/GL/glext.h             # [win]
    folder: GL                                                              # [win]
  - url: https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h         # [win]
    folder: KHR                                                             # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ compiler('c') }}
    - sysroot_linux-64 2.17              # [linux64]
    - make                               # [unix]
    - python          3.9                # [build_platform != target_platform]
    - cmake                              # [build_platform != target_platform]
    - numpy           1.20               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]

  host:
    - eman-deps         {{ emandeps }}
    - libglu                             # [linux]
    - python            3.9

  run:
    - eman-deps         {{ emandeps }}

test:
  requires:
    - eman-deps         {{ emandeps }}
    - openssh                            #[not win]

  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]

about:
  summary: Eman development package
