{% set repo   = "eman2" %}
{% set branch = "develop2" %}

package:
  name: eman-dev
  version: 2.39

source:
  - url: https://github.com/cryoem/{{ repo }}/archive/{{ branch }}.tar.gz
    fn: {{ repo }}-{{ branch }}.tar.gz
  - url: https://www.khronos.org/registry/OpenGL/api/GL/glext.h             # [win]
    folder: GL                                                              # [win]
  - url: https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h         # [win]
    folder: KHR                                                             # [win]

build:
  number: 0

requirements:
  build:
    - cmake 3.14.*
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]

  host:
    - eman-deps 18.0.*
    - libglu                             # [linux]

test:
  requires:
    - eman-deps 18.0.*
    - openssh                            #[not win]

  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]

about:
  summary: Eman development package
