channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
    - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
