channels:
  targets:
    - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: eman-feedstock

provider:
  linux: circle
  osx: github_actions
  win: github_actions

os_version:
  linux_64: cos7
