travis:
  secure:
    BINSTAR_TOKEN: bSPHqyVYxfnmmutdlk9jzvD8z5EaKO16RH47BbKZlhP+oo5SqL4YVkChC8pxd+UI/H/ZHx643WXG3azpXbDMncC4KPiLjx1M8nzCt2tTulkRHUqVDfqnL6IwvxohQHzaJAgHmcJ+wgw+IMRMtScBSw5ULrVrdupcDFeG3VURkz7NVG7Y7IuX6G2N8SKsitle+FAOXWqUEfpal7g02NJ6k+bYhw9POYyV+CFVWzrWvhLQX/dbpUude/lnNJDTIpZ7Uly5xgKPxWGpOuMdIekaJYtxmenCWuzOO4B1jnnQgPShK6koKMknNc+G/i9fZ0sj/ByDZIWzzgS6mTSj/TtKefyy7ELwbDVLz6HfakCGdZ1PYA99z3EKpa0ExXD/2fId0CLwpYziszOxMf0qwlzCJjais838FAn2qV361DsveOeZQgSey9rGfWFgH82NLlldLiZUYMnPMYRBfrtMZvGDsctr/xbK4Zn3jVHIU6fn0hJQ8RHW+O2GPGwroZgKjuU16bSVB7/9sSPdAAd22g8qxh0DWb14b4VKpcPhFMPnbMu/bVPf4v8IGbuH5jf/bqWRsxGA+M+7STIfdM+cNf+0OtKDOx31cHg3ZStQWT2gpi6J978HSLdYoiB/ck8NqVY8A1gBeJGYkP8SyREwOpIQbLQ307HH7NthVYY+74+q1PI=
appveyor:
  secure:
    BINSTAR_TOKEN: 8Bbfjp64oEvOo3rnhLhXmEhGf4T+JOy+AWB0WwSXZSbFqyBlWRNbW9G8aI/2liRz

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, dev]

github:
  user_or_org: cryoem
  repo_name: eman-feedstock
