travis:
  secure:
    BINSTAR_TOKEN: BUh5BfFXuNe3TjNKMy/re7qbD2ZleceuRa36BupwY6Am3C1YlkGvG9U3ti8S+/FzdibHTkcg5h52QI01VPVwQSLz5eqEYUgBdmzOTDiqIV0l/jHLceNQjMkm4XE+d8cbmqLVYFbxZ1v2FPET6WMAeeCzNrhf8Pbx8pHvhfWc77lqXujaxJ5XWD1BZo5DNV73ueFGCuJjy5PG0H2Spb7qB9kSgSEpGVqbny8JaYmIr+z5/Vq+UqIkteTLhg9oskKae63L5i695hVi9yc5jval5KaqbEC0sdzQ59aPoye6qCd5XgjndxBioULSwP7ceigMa7TzDbgUZC5HNuUzZueqpqjjBjB4+SCfYTjEfwnFNoXpEHlfWLmXMoa5WOSbqY+V3A4OrUd12yqVt/XJAe0DoUtH4OBbMQQLlFOahrPehnIosvX4adcNKGJ83qroRmIOM7ul7u7l9MCx7WMUeX2H5fonAcTnSz/VJ6gVe2WujYTuL/feI4u0AsZ8t2LDYWErQ6zx/7GVLVulSzhVdxHSDB46NAq2cGzRD95WPmsvg2bfhMQu0DM5bbMShP9c9ULGjRPlhVETTvjdzfqV3jnUS3jtEJZgH7Pr/2WCAlt4Dk3eR9zOHsW/C6j6TZLb1PpLpEZzUYe496GuUQHRDtSMWO7M1a/YWUhbA4QWsW7CuCM=
appveyor:
  secure:
    BINSTAR_TOKEN: 08VitP470QRyxFjl1XaJ0grdxR44Y9atVaHtnZYR8flgKDGTvOIQdRPEnWDoGFPk
