github:
  user_or_org: cryoem
  repo_name: eman-feedstock

channel_priority: flexible

provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
  linux_aarch64: github_actions

os_version:
  linux_64: cos7

build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
test_on_native_only: true
