name: Build for new tag
on: workflow_dispatch

jobs:
  update-version:
    runs-on: ubuntu-latest
    name: update-version
    steps:
      - name: Checkout eman-feedstock
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: python ./recipe/update-version.py
