name: Build for new tag
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New tag to build from passed by cryoem/eman2 actions'

jobs:
  update-version:
    runs-on: ubuntu-latest
    name: update-version
    steps:
      - name: Checkout eman-feedstock
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: python ./recipe/update-version.py
        env:
          new_version: ${{ inputs.new_version }}
